const products=[
['Pixie Cut','Pixie Cut','Natural Black','8 inch',191,'HD Lace','pixie-cut.jpg'],['Pixie Curls','Pixie Curls','Espresso','12 inch',222,'Transparent Lace','pixie-curls.jpg'],['Bone Straight','Bone Straight','Honey Blonde','16 inch',253,'4x4 Closure','bone-straight.jpg'],['Body Wave','Body Wave','Burgundy','20 inch',283,'5x5 Closure','body-wave-card.jpg'],['Deep Wave','Deep Wave','Natural Black','20 inch',314,'13x4 Lace Front','feature-deep.jpg'],['Water Wave','Water Wave','Blonde','20 inch',344,'HD Lace','feature-wave.jpg'],['Loose Wave','Loose Wave','Natural Black','24 inch',397,'Transparent Lace','body-wave.jpg'],['Loose Deep Waves','Loose Deep Waves','Burgundy','20 inch',497,'HD Lace','feature-deep.jpg'],['Straight Bob','Straight Bob','Pink','24 inch',500,'Transparent Lace','straight-bob.jpg'],['Curly Bob','Curly Bob','Blonde','30 inch',245,'4x4 Closure','straight-bob.jpg'],['Burmese Curly','Burmese Curly','Espresso','12 inch',229,'HD Lace','deep-curly.jpg'],['Deep Curly','Deep Curly','Pink','24 inch',337,'5x5 Closure','deep-curly.jpg'],['Afro Kinky','Afro Kinky','Blonde','30 inch',150,'13x4 Lace Front','afro-kinky.jpg'],['Layered Straight','Layered Straight','Natural Black','20 inch',245,'HD Lace','feature-deep.jpg'],['Layered Body Wave','Layered Body Wave','Natural Black','20 inch',339,'Transparent Lace','body-wave.jpg'],['Kinky Curly','Kinky Curly','Natural Black','18 inch',275,'4x4 Closure','deep-curly.jpg'],['Kinky Straight','Kinky Straight','Natural Black','20 inch',288,'5x5 Closure','bone-straight.jpg'],['Jerry Curl','Jerry Curl','Natural Black','16 inch',268,'HD Lace','body-wave-card.jpg'],['Jerry Straight','Jerry Straight','Natural Black','18 inch',299,'Transparent Lace','straight-bob.jpg'],['Bob Wig','Bob Wig','Honey Blonde','16 inch',319,'4x4 Closure','bone-straight.jpg']
];
const cats=['All styles','Pixie Cut','Pixie Curls','Bone Straight','Body Wave','Deep Wave','Water Wave','Loose Wave','Kinky Curly','Kinky Straight','Jerry Curl','Loose Deep Waves','Straight Bob','Curly Bob','Burmese Curly','Bob Wig','Jerry Straight','Deep Curly','Afro Kinky'];
let activeCat='All styles', cart=[], saved=[];
const $=s=>document.querySelector(s);
const money=n=>'$'+n.toLocaleString();
function renderChips(){ $('#chips').innerHTML=cats.map(c=>`<button class="chip ${activeCat===c?'active':''}" data-cat="${c}">${c}</button>`).join(''); document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat;renderChips();renderProducts()}) }
function filtered(){let q=$('#searchInput')?.value.toLowerCase()||'', len=$('#lengthFilter').value, tex=$('#textureFilter').value, col=$('#colorFilter').value, lace=$('#laceFilter').value;return products.filter(p=>(activeCat==='All styles'||p[0]===activeCat)&&(!q||p.join(' ').toLowerCase().includes(q))&&(len==='Any length'||p[3]===len)&&(tex==='Any texture'||p[1]===tex)&&(col==='Any color'||p[2]===col)&&(lace==='Any lace type'||p[5]===lace));}
function renderProducts(){let list=filtered();$('#resultCount').textContent=list.length?`1–${list.length}`:'0';$('#productGrid').innerHTML=list.map((p,i)=>`<article class="product-card"><div class="product-image"><img src="assets/${p[6]}" alt="${p[1]} wig"><span class="badge">${p[5].toUpperCase()}</span><button class="heart ${saved.includes(p[0])?'saved':''}" data-save="${p[0]}">${saved.includes(p[0])?'♥':'♡'}</button></div><div class="product-info"><span class="eyebrow">${p[0].toUpperCase()}</span><h3>${p[1]}</h3><div class="meta">${p[1]}<br>● ${p[2]} · ${p[3]}</div><div class="price-row"><span class="price">${money(p[4])}</span><span class="lace-tag">${p[5]}</span></div><select aria-label="Color for ${p[1]}"><option>${p[2]}</option><option>Natural Black</option><option>Espresso</option><option>Burgundy</option><option>Blonde</option><option>Pink</option></select><select aria-label="Length for ${p[1]}"><option>${p[3]}</option><option>12 inch</option><option>16 inch</option><option>20 inch</option><option>24 inch</option><option>30 inch</option></select><button class="add-btn" data-add="${p[0]}">ADD TO CART</button></div></article>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add));document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>toggleSave(b.dataset.save));}
function addCart(name){const p=products.find(x=>x[0]===name);cart.push(p);renderCart();openCart();}
function removeCart(i){cart.splice(i,1);renderCart()}
function renderCart(){ $('#cartCount').textContent=cart.length;let total=cart.reduce((a,p)=>a+p[4],0);$('#cartTotal').textContent=money(total);$('#cartItems').innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-line"><img src="assets/${p[6]}"><div><strong>${p[1]}</strong><br><small>${p[2]} · ${p[3]}</small><br>${money(p[4])}</div><button onclick="removeCart(${i})">×</button></div>`).join(''):'<p>Your bag is empty. Add a signature look to begin.</p>';}
function toggleSave(name){saved=saved.includes(name)?saved.filter(x=>x!==name):[...saved,name];$('#wishCount').textContent=saved.length;renderProducts();renderSaved();}
function renderSaved(){const items=products.filter(p=>saved.includes(p[0]));$('#savedGrid').innerHTML=items.length?items.map(p=>`<div class="saved-item"><img src="assets/${p[6]}"><p>${p[1]} · ${money(p[4])}</p></div>`).join(''):'<p>No saved looks yet.</p>';}
function openCart(){ $('#cartDrawer').classList.add('open');$('#overlay').classList.add('show') }
function closeCart(){ $('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('show') }
$('#cartBtn').onclick=openCart;$('#closeCart').onclick=closeCart;$('#overlay').onclick=closeCart;$('#wishlistBtn').onclick=()=>$('#saved').scrollIntoView({behavior:'smooth'});$('#menuBtn').onclick=()=>$('#mobileNav').classList.toggle('open');
['searchInput','lengthFilter','textureFilter','colorFilter','laceFilter'].forEach(id=>$('#'+id).addEventListener('input',renderProducts));$('#resetFilters').onclick=()=>{activeCat='All styles';$('#searchInput').value='';['lengthFilter','textureFilter','colorFilter','laceFilter'].forEach(id=>$('#'+id).selectedIndex=0);renderChips();renderProducts()};
document.querySelectorAll('[data-feature]').forEach(b=>b.onclick=()=>{activeCat=b.dataset.feature;renderChips();renderProducts();$('#collection').scrollIntoView({behavior:'smooth'})});
$('#creatorForm').addEventListener('submit',e=>{e.preventDefault();$('#formStatus').textContent='Application received. Thank you — the Noir Strands team will review your submission.';e.target.reset()});$('#checkoutCart').onclick=()=>{closeCart();$('#checkout').scrollIntoView({behavior:'smooth'})};
renderChips();renderProducts();renderCart();renderSaved();
